/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'hpcdocs' }],

  jupytersidebar: [
    {
      type: 'category',
      label: 'JupyterHub',
      // when you click the category, go to this doc:
      link: { type: 'doc', id: 'jupyter/jupyterhub-policy' },
      // but keep the children autogenerated from the folder:
      items: [{ type: 'autogenerated', dirName: 'jupyter' }],
    },
  ],

  // But you can create a sidebar manually
  /*
  jupyterSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'jupyter',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
   
};

export default sidebars;
